name: .NET CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/dotnet-build
        with:
          dotnet-version: 9.0.x
          configuration: Debug

      - name: Test
        run: dotnet test --no-build --verbosity normal