name: .NET CI/CD

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  pack-and-publish:
    if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Extract version from tag
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Add GitHub NuGet source
        run: dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

      - uses: ./.github/actions/dotnet-build
        with:
          dotnet-version: 9.0.x
          build-version: ${{ steps.get_version.outputs.version }}
          do-pack: true

      - name: Push to GitHub Packages
        run: dotnet nuget push **/*.nupkg --source github --skip-duplicate